- name: print variables
  hosts: localhost
  connection: local
  vars:
    COURSE: Aws Devops
    DURATION: 120 hrs
  tasks:
  - name: print course information
    vars:
    COURSE: azure devops
    ansible.builtin.debug:
      msg: "course is : {{COURSE}}, AND Duration is: {{DURATION}}"